-- Dynamic colors generated by matugen
return {
    primary = "rgba({{colors.primary.default.hex_stripped}}ee)",
    secondary = "rgba({{colors.secondary.default.hex_stripped}}ee)",
    inactive = "rgba({{colors.surface_variant.default.hex_stripped}}88)",
    background = "rgba({{colors.background.default.hex_stripped}}ee)",
}
