# vim:fileencoding=utf-8:foldmethod=marker
map ctrl+shift+f5 load_config_file

# Include active Matugen colors
include color.conf

# Include active toggle-theme configuration (HyDE or End4 style)
include kitty_theme.conf

# Always launch zsh (overrides inherited SHELL env from login session)
shell /usr/bin/zsh

# Disable confirmation when closing window
confirm_os_window_close 0
