# Kitty HyDE Theme Configuration

font_family             CaskaydiaCove Nerd Font Mono
font_size               12
cursor_shape            beam
background_opacity      0.90
url_style               curly
window_padding_width    10
enable_audio_bell       no
disable_ligatures       no
remember_window_size    no
sync_to_monitor         no

tab_bar_edge            top
tab_bar_align           left
tab_bar_style           separator
tab_separator           " "
tab_title_template      "   {title} "

